# This is the configuration used to check the rubocop source code.

#inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
#  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'private_pub.ru'
    - 'test/**/*'
    - 'db/*'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'bin/*'
    - 'app/helpers/*'
    - 'app/mailers/*'
    - 'app/jobs/*'
    - 'config.ru'
    - 'Rakefile'
    - 'app/channels/application_cable/*'

  TargetRubyVersion: 2.3

Layout/EmptyLinesAroundBlockBody:
  Enabled:
    - yes

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*

Style/IpAddresses:
  # The test for this cop includes strings that would cause offenses
  Exclude:
    - spec/rubocop/cop/style/ip_addresses_spec.rb

Layout/LineLength:
  Enabled:
    max: 250

Naming/VariableName:
  Enabled:
    - false

Style/SymbolArray:
  Enabled:
    - false

Layout/SpaceInLambdaLiteral:
  Enabled:
    - false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_class_methods
    - initializer
    - instance_methods
    - protected_methods
    - private_methods

# Trailing white space is meaningful in code examples
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Metrics/PerceivedComplexity:
  Enabled:
    - false

Metrics/CyclomaticComplexity:
  Enabled:
    - false

Lint/ShadowingOuterLocalVariable:
  Enabled:
    - false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Style/RedundantReturn:
  Enabled:
    - true

Style/ZeroLengthPredicate:
  Enabled:
    - false

Style/SafeNavigation:
  Enabled:
    - false

Style/GuardClause:
  Enabled:
    - true


Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/MethodLength:
  Enabled:
    max:
      - 15

Style/Documentation:
  Enabled:
    - false

Style/Lambda:
  Enabled:
    - false

Style/IfUnlessModifier:
  Enabled:
    - false

Style/RegexpLiteral:
  Enabled:
    - false

Metrics/AbcSize:
  Enabled:
    - true

Lint/BooleanSymbol:
  Enabled: false

Metrics/BlockLength:
  Enabled:
    - max: 40
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/config_obsoletion.rb

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

#RSpec/FilePath:
#  Exclude:
#    - spec/rubocop/formatter/junit_formatter_spec.rb
#
#RSpec/PredicateMatcher:
#  EnforcedStyle: explicit
#
#RSpec/MessageSpies:
#  EnforcedStyle: receive
#
#RSpec/NestedGroups:
#  Max: 7

Style/StringLiterals:
  Enabled:
    - double_quotes

Performance/Size:
  Exclude:
    - lib/example.rb
